#
#  ████████████████████████████████████████████████████████████████████████████████████████████
#  █▄─▄▄▀█▄─▄▄─██▀▄─██─▄─▄─█─█─███▄─▄▄▀█▄─▄▄▀█─▄▄─█▄─▄▄─███▄─▄▄─█▄─▄▄▀██▀▄─██─▄▄▄▄█▄─▄▄─█▄─▄▄▀█
#  ██─██─██─▄█▀██─▀─████─███─▄─████─██─██─▄─▄█─██─██─▄▄▄████─▄█▀██─▄─▄██─▀─██▄▄▄▄─██─▄█▀██─▄─▄█
#  ▀▄▄▄▄▀▀▄▄▄▄▄▀▄▄▀▄▄▀▀▄▄▄▀▀▄▀▄▀▀▀▄▄▄▄▀▀▄▄▀▄▄▀▄▄▄▄▀▄▄▄▀▀▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▀▄▄▀▄▄▄▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀

# !! Using Config to edit is not recommended use /dde <enable/disable> !!
drop_items: true
drop_experience: true
